require("rphast")
exampleArchive <- system.file("extdata", "examples.zip", package="rphast")
files <- c("ENr334.fa", "gencode.ENr334.gff", "rev.mod")
unzip(exampleArchive, files)
tm <- read.tm("rev.mod")
msa <- read.msa("ENr334.fa")
phastCons(msa, tm)
phastCons(msa, tm, estimate.trees=TRUE)
unlink(files)
