# here is a little portion of the SOL1 gene
align <- msa(c("ATGGCGACGAAGGCCGTGTGCGTGCTGAAGGGCGACGGCCCAGTGCAGGGCATCATCAATTTCGAGCAGAAGGCAAGGGCTGGGACGGAGGCTTGTTTGCGAGGCCGCTCCCACCCGCTCGTCCCCCCGCGCACCTTTGCTAGGAGCGGGTCGC----CCGCCAGGC-CTCGGGGCCGCCCTGGTCCAGCGCCCGGTCCCGGCCCGTGCCGCCCGGTCGGTGCCTTCGCCCCCAGCGGTGCGGTGCCCAAGTGCTGAGTCACCGGGCGGGCCCGGGC----GCGGGGCGTGGGA---------CCGAGGCCGCCGCGGG",
               "ATGGCGACGAAGGCCGTGTGCGTGCTGAAGGGCGATGGCCCAGTGCAGGGCATCATCAATTTCGAGCAGAAGGCAAGGGCTGGGACGGAGGCTTGTTTGCGAGGCCGCTCCTACCCGCTCGTCCCCCCGCGCACCTTTGCTAGGAGCGGGTCGC----CCGCCAGGC-CTCGGGGCTGCCCTGGTCCAGCGCCCGGTCCCGGCCCGTGCCGCCCGGTCGGTGCCTTCGCCCCCAGCGGTGCGGTGCCCAAGTGCTGAGTCACCGGGCGGGCCCGGGC----GCGGGGTGTGGGA---------CCGAGGCCGCCGCGGG",
               "ATGGCGATGAAAGCGGTGTGCGTGCTGAAGGGCGACGGTCCGGTGCAGGGAACCATCCACTTCGAGCAGAAGGCAAGGCCCGGGGC----------------------------------------------------GCGGGGCGCAGGCCGCGGTGACGCGGCGCACCTGTGCGGGAGCACGCCACGCCCCCG-CCACGGCCTGAG----------------------CCCG------------CTAAGTGCTGAGTCACC--GTGGCCTGGGGCAGGGGCTGGGCGCCGGGAAGCGAGGCCCGGGGC-GCCGC***"),
             names=c("hg19", "panTro2", "mm9"))

translate.msa(align)
translate.msa(msa(c("NNATGGCCACG")))
translate.msa(msa(c("NNATGGCCACG")), frame=3)
translate.msa(msa(c("NNATGGCCACG", "AT--GGCCACG")))
translate.msa(msa(c("NNATGGCCACG", "AT--GGCCACG")), one.frame=FALSE)
translate.msa(msa(c("NNATGGCCACG", "AT--GGCCACG")), one.frame=FALSE, frame=c(3,1))
